package com.jk.model;

import java.io.Serializable;

/*
 * 
 * 用户组
 * 
 */
public class Group  implements Serializable {

    private static final long serialVersionUID = 2365240725763441228L;
    //用户组id
    private Integer id;
    //用户组名称
    private String groupname;
    //用户组创建时间
    private String createtime;
    //用户组创建人
    private Integer createuserid;
    //用户组创建状态
    private String state;
    //用户组是否删除
    private String isdel;

    /**
     *
     * @return
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_group.groupname
     *
     * @return the value of jbbs_group.groupname
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     *
     * @param groupname
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     *
     * @return
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     *
     * @param createtime
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     *
     * @return
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     *
     * @param createuserid
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     *
     * @return
     */
    public String getState() {
        return state;
    }

    /**
     *
     * @param state
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     *
     * @return
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     *
     * @param isdel
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }
}